version: 1.0
os: linux
files:
  - source: /
    destination: /var/grassroot-messaging
permissions:
  - object: /var/grassroot-messaging
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/compilegrassroot.sh
    - location: scripts/stopgrassroot.sh
    - location: scripts/clearoldgrassroot.sh
    runas: root
  ApplicationStart:
    - location: scripts/startgrassroot.sh
      runas: root